# Generated by Django 4.1.3 on 2022-12-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(blank=True, default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='subject',
            field=models.CharField(blank=True, default='-', max_length=100),
        ),
    ]
