# Generated by Django 4.1.3 on 2022-12-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productreview_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='status',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='updated_at',
        ),
    ]
