# Generated by Django 4.1.3 on 2022-12-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productreview_created_at_alter_productreview_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='review',
        ),
        migrations.AddField(
            model_name='productreview',
            name='content',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
