# Generated by Django 4.1.3 on 2022-12-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_productreview_review_productreview_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='subject',
            new_name='title',
        ),
    ]
